notifications:
  email: false
matrix:
  include:
  - language: android
    android:
      components:
      - build-tools-28.0.3
      - android-28
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      - sys-img-x86-android-28
      - sys-img-armeabi-v7a-android-28
    before_install:
    - cd android
    - openssl aes-256-cbc -K $encrypted_05b154c8d8ea_key -iv $encrypted_05b154c8d8ea_iv
      -in release.jks.enc -out release.jks -d
    script:
    - cd android
    - "./gradlew clean assembleRelease"
